### ISSUE TITLE
Cannot find module './sqldb'

### ISSUE THREAD

**Issue by distobj** [sachac/explore-neighbourhood-libraries#1]
I'm pretty new to Node, but I'm getting this error when starting the server, and can't find much information about "sqldb" to debug this myself.

```
Error: Cannot find module './sqldb'
    at Function.Module._resolveFilename (module.js:336:15)
    at Function.Module._load (module.js:278:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (/home/mbaker/venvs/enl/src/explore-neighbourhood-libraries/server/app.js:7:30)
    at Module._compile (module.js:460:26)
    at normalLoader (/home/mbaker/venvs/enl/src/explore-neighbourhood-libraries/node_modules/babel-core/lib/api/register/node.js:199:5)
    at Object.require.extensions.(anonymous function) [as .js] (/home/mbaker/venvs/enl/src/explore-neighbourhood-libraries/node_modules/babel-core/lib/api/register/node.js:216:7)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
Stopping Express server
```

**Comment by sachac** [comment]
Sorry about that! It was because I hadn't correctly removed stuff I wasn't using. I've pushed a bunch more updates. With those, would either "grunt serve" or "node server/index.js" work for you?

**Comment by distobj** [comment]
Bingo! Thanks, this is extremely cool.

**Comment by sachac** [comment]
Heads up! =) I converted it to entirely client-side code, so all you need is Tampermonkey or Greasemonkey and the script. No more local server needed, and it doesn't need to re-scrape the page either!
